const $=s=>document.querySelector(s);let siteId=null,selectedCsv=null,forecastHours=24,chartState={power:[],forecast:[],weather:[]};
const pageKeys=new Set(['home','dashboard','upload','weather','forecast','investigations','fleet','savings','performance','cleaning','timing','warranty','discom','integrations','about']);
function showRoute(){let page=location.hash.slice(1);if(!pageKeys.has(page))page='home';document.querySelectorAll('[data-route]').forEach(view=>{view.hidden=view.dataset.route!==page});document.querySelectorAll('[data-page-link]').forEach(link=>{if(link.dataset.pageLink===page)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current')});document.title=`${page[0].toUpperCase()+page.slice(1)} · SolarSurd AI`;window.scrollTo({top:0,behavior:'auto'});if(siteId){renderCharts();window.refreshSolarFeatures?.()}}
window.addEventListener('hashchange',showRoute);showRoute();
const reportButton=document.createElement('button');reportButton.type='button';reportButton.className='header-button';reportButton.textContent='Download JSON';reportButton.onclick=async()=>{if(!siteId)return alert('Select a site first.');try{const r=await api(`/api/v1/sites/${siteId}/report`),blob=new Blob([JSON.stringify(r,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`solarsurd-site-${siteId}-report.json`;a.click();URL.revokeObjectURL(a.href)}catch(e){alert(e.message)}};document.querySelector('.header-actions').append(reportButton);
$('#printReport').onclick=()=>window.print();
$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark-mode');const dark=document.body.classList.contains('dark-mode');localStorage.setItem('solarsurd-theme',dark?'dark':'light');$('#themeToggle').textContent=dark?'Light mode':'Dark mode'};
if(localStorage.getItem('solarsurd-theme')==='dark'){document.body.classList.add('dark-mode');$('#themeToggle').textContent='Light mode'}
$('#logoutButton').onclick=async()=>{try{await fetch('/api/v1/auth/logout',{method:'POST'})}finally{location.replace('/login')}};
api('/api/v1/auth/me').then(x=>{$('#accountLabel').textContent=x.email||''}).catch(()=>{});
async function api(url,opts){if(location.protocol==='file:')throw Error('Dashboard is opened as a file. Start the backend with start_solar_surds.bat, then open http://127.0.0.1:8000.');const r=await fetch(url,opts);let d={};try{d=await r.json()}catch{}if(r.status===401){location.replace('/login');throw Error('Sign in again to continue.')}if(!r.ok){let detail=d.detail;if(Array.isArray(detail))detail=detail.map(x=>`${Array.isArray(x.loc)?x.loc.join('.'):'input'}: ${x.msg||JSON.stringify(x)}`).join('; ');else if(detail&&typeof detail==='object')detail=JSON.stringify(detail);throw Error(detail||r.statusText)}return d}
async function loadSites(){const sites=await api('/api/v1/sites');$('#siteSelect').innerHTML=`<option value="">${sites.length?'Choose a saved site':'No saved sites yet — create or load a sample'}</option>`+sites.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('#siteMessage').textContent=sites.length?`${sites.length} saved site${sites.length===1?'':'s'} available. Select one to view its dashboard.`:'No sites yet. Fill in the site details above and select Create site, or load the public sample.'}
$('#siteForm').onsubmit=async e=>{e.preventDefault();try{const x=Object.fromEntries(new FormData(e.target));for(const k of ['latitude','longitude','capacity_kw','performance_ratio','inverter_capacity_kw','tilt_deg','azimuth_deg'])x[k]=x[k]===''?null:Number(x[k]);if(!x.commissioned_on)x.commissioned_on=null;const s=await api('/api/v1/sites',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x)});await loadSites();$('#siteSelect').value=s.id;$('#siteMessage').textContent=`Created “${s.name}”. Add daily generation in Performance or upload inverter data.`;await selectSite()}catch(err){alert(err.message)}};
$('#siteSelect').onchange=()=>{selectSite();if($('#siteSelect').value)location.hash='dashboard'};
$('#forecastHorizon').onchange=e=>{forecastHours=Number(e.target.value);selectSite()};
const mapDefinitions=[
  ['timestamp','Timestamp / date', ['timestamp','time','date','datetime','local_time']],
  ['ac_power_w','AC power (W)',['ac_power_w','ac_power','active_power','power_ac','pac','power','w_avg']],
  ['energy_wh','Energy (Wh)',['energy_wh','energy','daily_energy','yield','e_day','wh_sum']],
  ['dc_power_w','DC power (W)',['dc_power_w','dc_power','power_dc','pdc']],
  ['irradiance_poa_wm2','Panel irradiance POA (W/m²)',['irradiance_poa_wm2','poa','poa_irradiance']],
  ['ghi_wm2','Global irradiance GHI (W/m²)',['ghi_wm2','ghi','global_irradiance']],
  ['ambient_temp_c','Ambient temperature (°C)',['ambient_temp_c','temperature','temp_c','air_temperature']],
  ['module_temp_c','Module temperature (°C)',['module_temp_c','module_temperature','cell_temperature']],
  ['dc_voltage_v','DC voltage (V)',['dc_voltage_v','dc_voltage','voltage_dc','vdc']],
  ['dc_current_a','DC current (A)',['dc_current_a','dc_current','current_dc','idc']]
];
function normalizedHeader(s){return s.replace(/^\uFEFF/,'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
function splitCsvHeader(line){const out=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'&&quoted){value+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===','&&!quoted){out.push(value);value=''}else value+=c}out.push(value);return out}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function previewCsv(file){selectedCsv=file;if(!file)return;file.text().then(text=>{const headers=splitCsvHeader((text.split(/\r?\n/,1)[0]||'').replace(/^\uFEFF/,''));if(headers.length<2)throw Error('Could not read a header row.');const preview=$('#csvPreview');preview.hidden=false;preview.innerHTML=`<div class="preview-heading"><div><b>${esc(file.name)}</b><span>${(file.size/1024).toFixed(1)} KB · Choose which columns represent each measurement.</span></div><button id="uploadMappedCsv" type="button">Validate & upload</button></div><div class="mapping-grid">${mapDefinitions.map(([key,label,aliases])=>{const found=headers.find(h=>aliases.includes(normalizedHeader(h)));return `<label>${esc(label)}${key==='timestamp'?'<em>Required</em>':''}<select data-map="${key}"><option value="">Not in file</option>${headers.map(h=>`<option value="${esc(h)}" ${h===found?'selected':''}>${esc(h)}</option>`).join('')}</select></label>`}).join('')}</div><p class="muted">We detected likely matches automatically. Review them before uploading; only selected columns will be used.</p>`;$('#uploadMappedCsv').onclick=uploadMappedCsv}).catch(err=>{$('#csvPreview').hidden=false;$('#csvPreview').textContent=err.message})}
async function uploadMappedCsv(){if(!siteId)return alert('Select or create a site first.');if(!selectedCsv)return;const mapping=Object.fromEntries([...$('#csvPreview').querySelectorAll('[data-map]')].map(s=>[s.dataset.map,s.value||null]));if(!mapping.timestamp)return alert('Map a date/time column first.');if(!mapping.ac_power_w&&!mapping.energy_wh&&!mapping.dc_power_w)return alert('Map at least one AC/DC power or energy column.');const fd=new FormData();fd.append('file',selectedCsv);fd.append('mapping',JSON.stringify(mapping));const button=$('#uploadMappedCsv');button.disabled=true;button.textContent='Validating…';try{const r=await api(`/api/v1/sites/${siteId}/ingest/csv`,{method:'POST',body:fd});$('#siteMessage').textContent=`Accepted ${r.accepted.toLocaleString()} rows · average data completeness ${r.mean_data_quality_score.toFixed(0)}%. Completeness is not accuracy.`;$('#csvPreview').hidden=true;selectedCsv=null;$('#csv').value='';await selectSite()}catch(err){$('#siteMessage').textContent=`CSV was not uploaded: ${err.message}`}finally{button.disabled=false;button.textContent='Validate & upload'}}
$('#csv').onchange=e=>previewCsv(e.target.files[0]);
const dropZone=$('#dropZone');dropZone.ondragover=e=>{e.preventDefault();dropZone.classList.add('dragging')};dropZone.ondragleave=()=>dropZone.classList.remove('dragging');dropZone.ondrop=e=>{e.preventDefault();dropZone.classList.remove('dragging');const file=e.dataTransfer.files[0];if(file)previewCsv(file)};dropZone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#csv').click()}};
$('#loadPvdaq').onclick=async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='Loading measured sample…';try{const r=await api('/api/v1/demo/pvdaq',{method:'POST'});await loadSites();$('#siteSelect').value=r.site.id;$('#siteMessage').textContent=`${r.existing?'Loaded saved':'Added'} public NREL PVDAQ system 1245 with ${r.accepted.toLocaleString()} measured readings. It is a separate sample site.`;await selectSite();location.hash='dashboard'}catch(err){alert(`Could not load the public sample: ${err.message}`)}finally{b.disabled=false;b.textContent='Load real public PVDAQ sample'}};
$('#simulatorForm').onsubmit=async e=>{e.preventDefault();if(!siteId){$('#simulatorResult').textContent='Create or select a site first; its saved capacity is the comparison baseline.';return}try{const x=Object.fromEntries(new FormData(e.target));for(const k of ['panel_count','panel_wattage_w','peak_sun_hours','losses_pct','inverter_capacity_kw','tariff_inr_per_kwh','export_tariff_inr_per_kwh','self_consumption_pct','installed_cost_inr','monthly_bill_inr','grid_co2_kg_per_kwh'])x[k]=x[k]===''?null:Number(x[k]);if(x.export_tariff_inr_per_kwh===null)x.export_tariff_inr_per_kwh=0;const r=await api(`/api/v1/sites/${siteId}/simulator`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x)});const fmt=n=>Number(n).toLocaleString('en-IN',{maximumFractionDigits:1});const block=(title,v)=>`<article class="sim-card"><h3>${title}</h3><b>${fmt(v.dc_capacity_kw)} kWp DC</b><p>${fmt(v.daily_kwh)} kWh/day · ${fmt(v.annual_kwh)} kWh/year</p><p>Estimated savings: ₹${fmt(v.monthly_savings_inr)}/month; ₹${fmt(v.annual_savings_inr)}/year</p>${v.annual_co2_avoided_kg==null?'':`<p>Estimated CO₂ avoided: ${fmt(v.annual_co2_avoided_kg)} kg/year</p>`}${v.payback_years==null?'':`<p>Simple payback: ${fmt(v.payback_years)} years</p>`}</article>`;$('#simulatorResult').innerHTML=`<div class="sim-results">${block('Current saved system',r.current)}${block('Proposed system',r.proposed)}</div><p><b>Change:</b> ${fmt(r.difference.daily_kwh)} kWh/day · ${fmt(r.difference.annual_kwh)} kWh/year · ₹${fmt(r.difference.annual_savings_inr)}/year savings</p><details><summary>Calculation assumptions</summary><ul>${r.assumptions.map(s=>`<li>${s}</li>`).join('')}</ul></details>`}catch(err){$('#simulatorResult').textContent=`Could not calculate: ${err.message}`}};
async function selectSite(){
  siteId=$('#siteSelect').value;if(!siteId){chartState={power:[],forecast:[],weather:[]};$('#energy').textContent='—';$('#yield').textContent='Specific yield —';$('#quality').textContent='—';$('#efficiency').textContent='—';$('#anomalies').textContent='No site selected.';$('#weatherStatus').textContent='Select a site to load weather context.';$('#bestWindow').textContent='Select a site for the model\'s brightest forecast hours.';renderCharts();return}
  const [m,a,f,s]=await Promise.all([api(`/api/v1/sites/${siteId}/metrics`),api(`/api/v1/sites/${siteId}/anomalies`),api(`/api/v1/sites/${siteId}/forecast?hours=${forecastHours}`),api(`/api/v1/sites/${siteId}/series?limit=2000`)]);
  $('#energy').textContent=m.energy_kwh==null?'—':`${m.energy_kwh.toFixed(2)} kWh`;
  $('#yield').textContent=`Specific yield ${m.specific_yield_kwh_per_kwp==null?'—':m.specific_yield_kwh_per_kwp.toFixed(2)+' kWh/kWp'}`;
  $('#quality').textContent=m.mean_data_quality_score==null?'—':`${m.mean_data_quality_score.toFixed(0)}%`;
  $('#efficiency').textContent=m.mean_inverter_efficiency_pct==null?'—':`${m.mean_inverter_efficiency_pct.toFixed(1)}%`;
  chartState.power=s.points;chartState.forecast=f.points;renderCharts();
  $('#anomalies').innerHTML=a.items.length?a.items.map(x=>`<div class="investigation"><b>${x.duration_samples} samples: ${x.residual_w} W deviation</b><p>${esc(x.evidence)}</p><small>${esc(x.start)} – ${esc(x.end)}</small></div>`).join(''):'No persistent residual investigations from available records.';
  $('#alertStatus').textContent=a.items.length?`${a.items.length} investigation ${a.items.length===1?'signal':'signals'} to review. These are on-screen indicators, not confirmed faults.`:'No persistent investigation signals in this dataset.';
  $('#forecastText').textContent=f.points.length?`${f.points.length} points · repeats recent measured power. Shaded range is historic min/max, not a calibrated forecast interval.`:'No history available for a persistence baseline.';
  const spanDays=m.history_days||0;
  $('#healthStatus').textContent=spanDays>=365?`${Math.round(spanDays)} days of records. No degradation rate is calculated by this prototype.`:`${Math.round(spanDays)} days of records. Long-term health trend needs about 365 days of comparable data; no degradation rate is shown.`;
  const gaps=s.points.filter(p=>p.actual_power_w!=null&&p.expected_power_w!=null&&p.expected_basis).map(p=>Math.max(0,p.expected_power_w-p.actual_power_w));
  $('#cleaningStatus').textContent=gaps.length?`A simple irradiance baseline shows a positive gap in ${gaps.filter(x=>x>0).length} of ${gaps.length} readings (average gap ${Math.round(gaps.reduce((x,y)=>x+y,0)/gaps.length)} W). This is not a soiling diagnosis.`:'No measured irradiance baseline is available to estimate a cleaning opportunity.';
  try{const w=await api(`/api/v1/sites/${siteId}/weather`);chartState.weather=w.items;$('#weatherStatus').textContent=w.items.length?`${w.items.length} hourly points · ${w.source}. Model-derived, not panel sensors.`:'Weather unavailable; telemetry remains accessible.';renderCharts();const bright=w.items.slice(0,24).filter(x=>(x.ghi_wm2||0)>0).sort((x,y)=>y.ghi_wm2-x.ghi_wm2).slice(0,3).sort((x,y)=>x.timestamp.localeCompare(y.timestamp));$('#bestWindow').textContent=bright.length?`Brightest modeled hours in the next day: ${bright.map(x=>new Date(x.timestamp).toLocaleTimeString([], {hour:'numeric'})).join(', ')} (shortwave radiation estimate).`:'No daytime irradiance forecast available.'}catch{chartState.weather=[];$('#weatherStatus').textContent='Weather unavailable; telemetry remains accessible.';$('#bestWindow').textContent='No weather forecast available.';renderCharts()}
  loadFleet();window.refreshSolarFeatures?.();
}
function renderCharts(){drawPowerChart(chartState.power);drawForecastChart(chartState.forecast);drawWeatherChart(chartState.weather)}
function canvasContext(selector,height){const c=$(selector);if(!c)return null;const w=Math.max(280,c.clientWidth||560),dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=height*dpr;c.style.height=`${height}px`;const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,height);return {c,ctx,w,h:height}}
function drawPowerChart(points){const z=canvasContext('#chart',220);if(!z)return;const {ctx,w,h}=z,pts=points.filter(p=>p.actual_power_w!=null||p.expected_power_w!=null),legend=document.querySelector('.chart-legend');if(legend){legend.children[0].hidden=!pts.some(p=>p.actual_power_w!=null);legend.children[1].hidden=!pts.some(p=>p.expected_power_w!=null)}if(!pts.length){ctx.fillStyle='#718178';ctx.fillText('Upload readings to see production.',16,30);return}const pad={l:52,r:14,t:14,b:32},iw=w-pad.l-pad.r,ih=h-pad.t-pad.b,max=Math.max(1,...pts.flatMap(p=>[p.actual_power_w||0,p.expected_power_w||0]));ctx.font='11px system-ui';for(let i=0;i<4;i++){const y=pad.t+ih*i/3;ctx.strokeStyle='#e5ece7';ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillStyle='#748078';ctx.fillText(`${Math.round(max*(1-i/3))} W`,2,y+4)}for(const [key,color] of [['expected_power_w','#d99a42'],['actual_power_w','#168454']]){ctx.beginPath();ctx.lineWidth=2.5;ctx.strokeStyle=color;let started=false;pts.forEach((p,i)=>{const v=p[key];if(v==null){started=false;return}const x=pad.l+iw*i/Math.max(1,pts.length-1),y=pad.t+ih*(1-v/max);if(!started){ctx.moveTo(x,y);started=true}else ctx.lineTo(x,y)});ctx.stroke()}ctx.fillStyle='#718178';ctx.fillText('Earlier readings',pad.l,h-8);ctx.textAlign='right';ctx.fillText('Latest',w-pad.r,h-8);ctx.textAlign='left'}
function drawForecastChart(points){const z=canvasContext('#forecastChart',190);if(!z)return;const {ctx,w,h}=z;if(!points.length){ctx.fillStyle='#718178';ctx.fillText('Forecast appears when measured history is available.',12,28);return}const pad={l:46,r:12,t:12,b:24},iw=w-pad.l-pad.r,ih=h-pad.t-pad.b,max=Math.max(1,...points.map(p=>p.upper_w||p.power_w||0));ctx.font='10px system-ui';for(let i=0;i<3;i++){const y=pad.t+ih*i/2;ctx.strokeStyle='#e5ece7';ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillStyle='#718178';ctx.fillText(`${Math.round(max*(1-i/2))} W`,2,y+3)}const x=i=>pad.l+iw*i/Math.max(1,points.length-1),y=v=>pad.t+ih*(1-(v||0)/max);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(x(i),y(p.upper_w)):ctx.moveTo(x(i),y(p.upper_w)));for(let i=points.length-1;i>=0;i--)ctx.lineTo(x(i),y(points[i].lower_w));ctx.closePath();ctx.fillStyle='#2d987d25';ctx.fill();ctx.strokeStyle='#168454';ctx.lineWidth=2;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(x(i),y(p.power_w)):ctx.moveTo(x(i),y(p.power_w)));ctx.stroke()}
function drawWeatherChart(points){const z=canvasContext('#weatherChart',190);if(!z)return;const {ctx,w,h}=z;if(!points.length){ctx.fillStyle='#718178';ctx.fillText('Weather context will appear when reachable.',12,28);return}const pad={l:38,r:36,t:12,b:25},iw=w-pad.l-pad.r,ih=h-pad.t-pad.b,maxI=Math.max(1,...points.map(p=>p.ghi_wm2||0)),temps=points.map(p=>p.ambient_temp_c).filter(x=>x!=null),minT=temps.length?Math.min(...temps):0,maxT=temps.length?Math.max(...temps):1;points.forEach((p,i)=>{const bw=Math.max(2,iw/points.length*.62),x=pad.l+iw*i/Math.max(1,points.length-1);const bh=ih*(p.ghi_wm2||0)/maxI;ctx.fillStyle='#e6ae4f99';ctx.fillRect(x-bw/2,pad.t+ih-bh,bw,bh)});ctx.strokeStyle='#1688a0';ctx.lineWidth=2;ctx.beginPath();let started=false;points.forEach((p,i)=>{if(p.ambient_temp_c==null)return;const x=pad.l+iw*i/Math.max(1,points.length-1),y=pad.t+ih*(1-(p.ambient_temp_c-minT)/Math.max(1,maxT-minT));if(!started){ctx.moveTo(x,y);started=true}else ctx.lineTo(x,y)});ctx.stroke();ctx.fillStyle='#a47732';ctx.font='10px system-ui';ctx.fillText('Irradiance',4,12);ctx.fillStyle='#1688a0';ctx.fillText('Temp',w-32,12)}
async function loadFleet(){try{const sites=await api('/api/v1/sites');if(!sites.length){$('#fleetList').textContent='Create a site or load the public sample.';return}const items=await Promise.all(sites.map(async site=>({site,metrics:await api(`/api/v1/sites/${site.id}/metrics`)})));$('#fleetList').innerHTML=items.sort((a,b)=>(b.metrics.energy_kwh||0)-(a.metrics.energy_kwh||0)).map(x=>`<button class="fleet-row" data-site="${x.site.id}"><span><b>${esc(x.site.name)}</b><small>${x.site.capacity_kw} kWp</small></span><strong>${x.metrics.energy_kwh==null?'—':x.metrics.energy_kwh.toFixed(1)+' kWh'}</strong><i>${x.metrics.mean_data_quality_score==null?'—':Math.round(x.metrics.mean_data_quality_score)+'% complete'}</i></button>`).join('');$('#fleetList').querySelectorAll('[data-site]').forEach(b=>b.onclick=()=>{$('#siteSelect').value=b.dataset.site;selectSite();location.hash='dashboard'})}catch{$('#fleetList').textContent='Fleet summary unavailable.'}}
window.addEventListener('resize',()=>{if(siteId)renderCharts()});
loadSites().then(()=>{if($('#siteSelect').options.length>1){$('#siteSelect').selectedIndex=1;selectSite().catch(err=>{$('#siteMessage').textContent=err.message})}}).catch(err=>{$('#siteMessage').textContent=err.message;$('#siteSelect').innerHTML='<option value="">Sign in or start the backend</option>'});
